In [1]:
import torch

/home/zyl/disk/poetry_env/algorithms-ai-IgVB5U1f-py3.10/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
T1 = torch.Tensor(3,3)
T2 = torch.Tensor(3,3)

In [12]:
T1

tensor([[3.7559e-01, 3.0850e-41, 3.9863e-01],
        [3.0850e-41, 1.1210e-43, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 3.6905e-01]])

In [13]:
T2

tensor([[3.8614e-01, 3.0850e-41, 4.2421e-01],
        [3.0850e-41, 8.9683e-44, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 3.7695e-01]])

In [14]:
torch.stack((T1,T2),dim=0)
# 沿着第一个维度进行拼接，扩充在第一维度，相当于直接把两个张量合起来，【2,】

tensor([[[3.7559e-01, 3.0850e-41, 3.9863e-01],
         [3.0850e-41, 1.1210e-43, 0.0000e+00],
         [8.9683e-44, 0.0000e+00, 3.6905e-01]],

        [[3.8614e-01, 3.0850e-41, 4.2421e-01],
         [3.0850e-41, 8.9683e-44, 0.0000e+00],
         [1.1210e-43, 0.0000e+00, 3.7695e-01]]])

In [16]:
torch.stack((T1,T2),dim=1)
# 沿着第二个维度进行拼接，扩充在第二维度，相当于【。，2，。】把每个张量第二维度的值进行拼接

tensor([[[3.7559e-01, 3.0850e-41, 3.9863e-01],
         [3.8614e-01, 3.0850e-41, 4.2421e-01]],

        [[3.0850e-41, 1.1210e-43, 0.0000e+00],
         [3.0850e-41, 8.9683e-44, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 3.6905e-01],
         [1.1210e-43, 0.0000e+00, 3.7695e-01]]])

In [17]:
torch.stack((T1,T2),dim=2)
# 沿着第三个维度进行拼接，扩充在第三维度，相当于把第三维度的值相对应进行拼接，【。，。，2】，最后一个维度就是元素维度，最小维度，所以dim不能超过这个值

tensor([[[3.7559e-01, 3.8614e-01],
         [3.0850e-41, 3.0850e-41],
         [3.9863e-01, 4.2421e-01]],

        [[3.0850e-41, 3.0850e-41],
         [1.1210e-43, 8.9683e-44],
         [0.0000e+00, 0.0000e+00]],

        [[8.9683e-44, 1.1210e-43],
         [0.0000e+00, 0.0000e+00],
         [3.6905e-01, 3.7695e-01]]])

In [24]:
torch.arange(10).type(torch.float)[None].shape


torch.Size([1, 10])

In [25]:
torch.arange(0, 10, dtype=torch.float).unsqueeze(-1).shape


torch.Size([10, 1])

In [26]:
torch.arange(0, 3, dtype=torch.float).unsqueeze(-1)

tensor([[0.],
        [1.],
        [2.]])

In [28]:
a = torch.randint(1,5,(5,4))

In [29]:
a

tensor([[3, 3, 4, 4],
        [3, 4, 1, 4],
        [3, 4, 1, 2],
        [2, 1, 3, 4],
        [1, 2, 2, 1]])

In [35]:
a[..., None, 1::2].shape

torch.Size([5, 1, 2])

In [34]:
a[..., 1::2].shape

torch.Size([5, 2])

In [47]:
a.repeat(3, 1,1)

tensor([[[3, 3, 4, 4],
         [3, 4, 1, 4],
         [3, 4, 1, 2],
         [2, 1, 3, 4],
         [1, 2, 2, 1]],

        [[3, 3, 4, 4],
         [3, 4, 1, 4],
         [3, 4, 1, 2],
         [2, 1, 3, 4],
         [1, 2, 2, 1]],

        [[3, 3, 4, 4],
         [3, 4, 1, 4],
         [3, 4, 1, 2],
         [2, 1, 3, 4],
         [1, 2, 2, 1]]])

In [48]:
a.repeat(3, 1,1)[..., None, 1::2].shape

torch.Size([3, 5, 1, 2])

In [45]:
a.repeat(3, 1,1)[..., 1::2].shape

torch.Size([3, 5, 2])

In [42]:
([1] * 2)

[1, 1]

In [49]:
b= a.repeat(3, 1,1)

In [50]:
b

tensor([[[3, 3, 4, 4],
         [3, 4, 1, 4],
         [3, 4, 1, 2],
         [2, 1, 3, 4],
         [1, 2, 2, 1]],

        [[3, 3, 4, 4],
         [3, 4, 1, 4],
         [3, 4, 1, 2],
         [2, 1, 3, 4],
         [1, 2, 2, 1]],

        [[3, 3, 4, 4],
         [3, 4, 1, 4],
         [3, 4, 1, 2],
         [2, 1, 3, 4],
         [1, 2, 2, 1]]])

In [55]:
b[..., None, 1::2].shape

torch.Size([3, 5, 1, 2])

In [54]:
b[..., 1::2].shape

torch.Size([3, 5, 2])

In [59]:
b[..., 1::2].repeat_interleave(2, dim=-1).shape

torch.Size([3, 5, 4])

In [58]:
b[..., None, 1::2].repeat_interleave(2, dim=-1).shape

torch.Size([3, 5, 1, 4])

In [60]:
a = torch.randint(1,9,(4,5,6,6)) 

In [61]:
a

tensor([[[[5, 1, 3, 4, 6, 7],
          [1, 4, 4, 8, 7, 2],
          [7, 3, 4, 2, 2, 4],
          [5, 7, 1, 8, 8, 8],
          [3, 4, 7, 3, 2, 8],
          [5, 4, 7, 4, 1, 1]],

         [[2, 1, 2, 2, 6, 8],
          [5, 6, 6, 7, 2, 7],
          [1, 5, 2, 5, 1, 8],
          [6, 4, 7, 4, 5, 8],
          [3, 6, 5, 4, 3, 3],
          [8, 3, 4, 5, 1, 5]],

         [[4, 3, 3, 3, 2, 1],
          [5, 6, 3, 1, 3, 2],
          [8, 1, 1, 6, 7, 3],
          [1, 5, 2, 6, 7, 5],
          [7, 4, 8, 2, 2, 3],
          [3, 2, 7, 8, 4, 2]],

         [[1, 4, 2, 6, 7, 7],
          [5, 4, 8, 3, 7, 7],
          [1, 1, 1, 8, 8, 3],
          [2, 6, 6, 5, 1, 2],
          [1, 3, 7, 8, 2, 5],
          [1, 7, 1, 6, 2, 6]],

         [[3, 2, 4, 6, 3, 2],
          [2, 4, 8, 1, 8, 7],
          [2, 4, 2, 8, 5, 7],
          [4, 2, 2, 5, 7, 1],
          [8, 4, 4, 8, 8, 3],
          [3, 1, 5, 1, 5, 3]]],


        [[[6, 5, 1, 8, 4, 3],
          [1, 2, 1, 3, 3, 4],
          [3, 1, 3, 3, 4, 8]

In [62]:
mask = torch.Tensor([[1,1,1,0,0,0],[1,1,1,1,0,0],[1,1,0,0,0,0],[1,1,1,1,1,1]])

In [63]:
mask

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [69]:
(a - torch.tril(torch.ones_like(a), -1) * 1e12)[2][0]

tensor([[ 7.0000e+00,  6.0000e+00,  6.0000e+00,  6.0000e+00,  6.0000e+00,
          2.0000e+00],
        [-1.0000e+12,  3.0000e+00,  4.0000e+00,  6.0000e+00,  4.0000e+00,
          3.0000e+00],
        [-1.0000e+12, -1.0000e+12,  2.0000e+00,  1.0000e+00,  6.0000e+00,
          6.0000e+00],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12,  2.0000e+00,  4.0000e+00,
          7.0000e+00],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,  7.0000e+00,
          8.0000e+00],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,
          2.0000e+00]])

In [70]:
(a - (1 - torch.triu(torch.ones_like(a), diagonal=0)) * 1e12)[2][0]

tensor([[ 7.0000e+00,  6.0000e+00,  6.0000e+00,  6.0000e+00,  6.0000e+00,
          2.0000e+00],
        [-1.0000e+12,  3.0000e+00,  4.0000e+00,  6.0000e+00,  4.0000e+00,
          3.0000e+00],
        [-1.0000e+12, -1.0000e+12,  2.0000e+00,  1.0000e+00,  6.0000e+00,
          6.0000e+00],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12,  2.0000e+00,  4.0000e+00,
          7.0000e+00],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,  7.0000e+00,
          8.0000e+00],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,
          2.0000e+00]])

In [71]:
pad_mask = mask.unsqueeze(1).unsqueeze(1).expand(a.shape[0], a.shape[1], a.shape[2], a.shape[3])
a * pad_mask - (1 - pad_mask) * 1e12

tensor([[[[ 5.0000e+00,  1.0000e+00,  3.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 1.0000e+00,  4.0000e+00,  4.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 7.0000e+00,  3.0000e+00,  4.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 5.0000e+00,  7.0000e+00,  1.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 3.0000e+00,  4.0000e+00,  7.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 5.0000e+00,  4.0000e+00,  7.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12]],

         [[ 2.0000e+00,  1.0000e+00,  2.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 5.0000e+00,  6.0000e+00,  6.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 1.0000e+00,  5.0000e+00,  2.0000e+00, -1.0000e+12, -1.0000e+12,
           -1.0000e+12],
          [ 6.0000e+00,  4.0000e+00,  7.0000e+00, -1.0000e+12, -1.0000e+12,
           -1

In [75]:
(a * pad_mask - (1 - pad_mask) * 1e12)[0][0]

tensor([[ 5.0000e+00,  1.0000e+00,  3.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 1.0000e+00,  4.0000e+00,  4.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 7.0000e+00,  3.0000e+00,  4.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 5.0000e+00,  7.0000e+00,  1.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 3.0000e+00,  4.0000e+00,  7.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 5.0000e+00,  4.0000e+00,  7.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12]])

In [72]:
def sequence_masking(x, mask, value='-inf', axis=None):
    """为序列条件mask的函数
    mask: 形如(batch_size, seq_len)的0-1矩阵；
    value: mask部分要被替换成的值，可以是'-inf'或'inf'；
    axis: 序列所在轴，默认为1；
    除了mask的地方替换，其他地方值不变
    x = torch.randint(1,10,(2,4,3,3))
    mask = torch.Tensor([[1,1,0],[1,0,0]])
    mask2 = torch.unsqueeze(mask, 1)
    mask2 = torch.unsqueeze(mask2, 1)
    """
    if mask is None:
        return x
    else:
        if value == '-inf':
            value = -1e12
        elif value == 'inf':
            value = 1e12
        assert axis > 0, 'greater than 0'
        # attention_mask.unsqueeze(1).unsqueeze(1).expand(batch_size, self.ent_type_size, seq_len, seq_len)

        # 中间维度补
        for _ in range(axis - 1):
            mask = torch.unsqueeze(mask, 1)  # [b,1。。。1，s]
        # 其余维度补
        for _ in range(x.ndim - mask.ndim):
            mask = torch.unsqueeze(mask, mask.ndim)  # [b,1,s,1]
        return x * mask + value * (1 - mask)

In [76]:
(sequence_masking(sequence_masking(a, mask, '-inf', a.ndim - 2), mask, '-inf', a.ndim - 1))[0][0]

tensor([[ 5.0000e+00,  1.0000e+00,  3.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 1.0000e+00,  4.0000e+00,  4.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [ 7.0000e+00,  3.0000e+00,  4.0000e+00, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,
         -1.0000e+12],
        [-1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12, -1.0000e+12,
         -1.0000e+12]])

In [77]:
a = torch.randint(1,5,(2,3))

In [78]:
b = torch.randint(1,5,(2,3))

In [79]:
a

tensor([[3, 2, 1],
        [2, 3, 1]])

In [80]:
b

tensor([[4, 4, 4],
        [3, 4, 3]])

In [82]:
torch.sum(a+b)

tensor(34)

In [83]:
torch.sum(a+b,dim=1)

tensor([18, 16])

In [84]:
a+b

tensor([[7, 6, 5],
        [5, 7, 4]])

In [86]:
torch.mean(torch.sum(a+b,dim=1).type(torch.float16))

tensor(17., dtype=torch.float16)

In [87]:
torch.mean(torch.sum(a+b).type(torch.float16))

tensor(34., dtype=torch.float16)

In [91]:
a = torch.randint(2,6,(2,3,4))

In [93]:
a

tensor([[[2, 2, 5, 2],
         [4, 5, 5, 5],
         [5, 5, 2, 3]],

        [[4, 5, 4, 3],
         [2, 5, 5, 3],
         [3, 5, 5, 2]]])

In [92]:
pos = torch.randint(2,6,(1,3,4))

In [94]:
pos

tensor([[[2, 2, 3, 2],
         [3, 5, 2, 4],
         [4, 4, 4, 5]]])

In [95]:
def apply_rotary_position_embeddings(position_embeddings, *tensors):
    """应用RoPE到tensors中
        其中，sinusoidal.shape=[1, n, d]，tensors为tensor的列表，而
        tensor.shape=[b, n, ..., d]。
    """
    cos_pos = position_embeddings[..., 1::2].repeat_interleave(2, dim=-1)
    sin_pos = position_embeddings[..., ::2].repeat_interleave(2, dim=-1)

    outputs = []
    for tensor in tensors:
        tensor2 = torch.stack([-tensor[..., 1::2], tensor[..., ::2]], -1)
        tensor2 = tensor2.reshape(tensor.shape)
        outputs.append(tensor * cos_pos + tensor2 * sin_pos)
    return outputs[0] if len(outputs) == 1 else outputs

In [96]:
apply_rotary_position_embeddings(pos, a)

tensor([[[ 0,  8,  4, 19],
         [ 5, 37, 10, 30],
         [ 0, 40, -2, 23]],

        [[-2, 18, -1, 18],
         [-5, 31, 14, 22],
         [-8, 32, 17, 30]]])

In [97]:
pos

tensor([[[2, 2, 3, 2],
         [3, 5, 2, 4],
         [4, 4, 4, 5]]])

In [98]:
a

tensor([[[2, 2, 5, 2],
         [4, 5, 5, 5],
         [5, 5, 2, 3]],

        [[4, 5, 4, 3],
         [2, 5, 5, 3],
         [3, 5, 5, 2]]])

In [99]:
p2 = pos.repeat(2,1,1)

In [100]:
p2

tensor([[[2, 2, 3, 2],
         [3, 5, 2, 4],
         [4, 4, 4, 5]],

        [[2, 2, 3, 2],
         [3, 5, 2, 4],
         [4, 4, 4, 5]]])

In [101]:
apply_rotary_position_embeddings(p2, a)

tensor([[[ 0,  8,  4, 19],
         [ 5, 37, 10, 30],
         [ 0, 40, -2, 23]],

        [[-2, 18, -1, 18],
         [-5, 31, 14, 22],
         [-8, 32, 17, 30]]])

In [102]:
a = torch.randint(2,6,(4,6))

In [103]:
a

tensor([[3, 3, 5, 3, 5, 4],
        [5, 4, 4, 4, 4, 3],
        [4, 3, 3, 3, 4, 2],
        [3, 2, 2, 4, 4, 4]])